version: "3.8"

services:
  # Aplicación principal
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: business-dates-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOLIDAY_API_URL=${HOLIDAY_API_URL:-https://content.capta.co/Recruitment/WorkingDays.json}
      - CACHE_TTL_MINUTES=${CACHE_TTL_MINUTES:-60}
      - API_TIMEOUT_MS=${API_TIMEOUT_MS:-10000}
      - MAX_RETRIES=${MAX_RETRIES:-3}
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - business-dates-network

  # Nginx como reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: business-dates-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - business-dates-network
    profiles:
      - production

networks:
  business-dates-network:
    driver: bridge

volumes:
  app-data:
    driver: local
